### ISSUE TITLE
Any development timeline?

### ISSUE THREAD

**Issue by azriel91** [eno-lang/enors#2]
Hiya! Saw this and thought it looked interesting as a TOML alternative (especially around deep levels of array-of-table nesting). Are you planning to work on the Rust library in the foreseeable future?

**Comment by simonrepp** [comment]
Hey! Thanks for your interest :) My current estimation would be that I'll continue work on enors around christmas - the last weeks I had to get some freelance work done to cross-finance the whole time I'm spending on eno's ecosystem ;), the coming weeks I'd like to finish the enophp implementation which is already halfway there, and then I'm very much looking forward to some rust finally :)

**Comment by azriel91** [comment]
cool thanks!
